name = "Barriers"
uuid = "be6cf53a-a3bb-40b3-b177-46b1316354c6"
authors = ["arzwa <arthur.zwaenepoel@gmail.com>"]
version = "0.1.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
AdaptiveProposals = "4f94ad4c-fdf5-4e90-bb89-27393c150f18"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Fwd = "12d7096c-2637-4d3e-9e8f-4c419b333460"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
ThreadTools = "dbf13d8f-d36e-4350-8970-f3a99faba1a8"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
WrightDistribution = "f1082b7d-a10b-4e22-9c8a-8cfeebeb2a60"

[compat]
Accessors = "0.1.38"
CSV = "0.10.15"
Combinatorics = "1.0.2"
DataFrames = "1.7.0"
KernelDensity = "0.6.9"
Plots = "1.40.9"
Printf = "1.11.0"
ProgressMeter = "1.10.4"
PyCall = "1.96.4"
Setfield = "1.1.2"
SpecialFunctions = "2.4.0"
StatsPlots = "0.15.7"
ThreadTools = "0.2.0"
Turing = "0.35.2"
